public enum Text_ID {
    Draw,
    DrawInfo,
    NormalSummon,
    Battle_1,
    SelectCommand_1,
    SelectCommand_2,
    GetAttackTarget,
    DirectAttack,
    Attack_1,
    Attack_2,
    Attack_3,
    Destroy,
    ActivateEffect,
}